swagger: "2.0"
info:
  description: "Chiamate API relative all'accesso e alla creazione del token."
  version: "1.0.0"
  title: "R.A.O. API"
  contact:
    email: "apiteam@swagger.io"
host: "rao.spid.app"
basePath: "/v2"
tags:
- name: "Authorization"
  description: "Api relative all'accesso di un operatore"
  externalDocs:
    description: "git R.A.O. pubblico"
    url: "https://github.com/Sielte/rao-pubblico"
- name: "Generate token"
  description: "Generazione di una richiesta di identificazione"
  externalDocs:
    description: "git R.A.O. pubblico"
    url: "https://github.com/Sielte/rao-pubblico"
schemes:
- "https"
- "http"
paths:
  /auth:
    post:
      tags:
      - "Authorization"
      summary: "Ottieni un token di sessione inserendo username e password"
      description: ""
      operationId: "auth"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "payload"
        description: "User e password dell'operatore"
        required: true
        schema:
          $ref: "#/definitions/Auth"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiAuthResponse"
  /token:
    post:
      tags:
      - "Generate token"
      summary: "Creazione della richiesta di identificazione"
      description: ""
      operationId: "token"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "header"
        description: "Header contenente il token di autorizzazione"
        required: true
        schema:
          $ref: "#/definitions/Header"
      - in: "body"
        name: "payload"
        description: "User e password dell'operatore"
        required: true
        schema:
          $ref: "#/definitions/UserDetail"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiAuthResponse"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Header:
    type: "object"
    required:
    - "Authorization"
    properties:
        Authorization:
          type: "string"
          example: "eyJ1c2VybmFtZSI6IkNpYW8ifQ:1lWcPE:a-vukHyF6j_sAxiHWSJ78wjeEqw"
  Auth:
    type: "object"
    required:
    - "username"
    - "password"
    properties:
      username:
        type: "string"
        example: "RSSMRA80A01C351O"
      password:
        type: "string"
        example: "LaMiaPass123!"
  UserDetail:
    type: "object"
    required:
    - "fiscalNumber"
    - "name"
    properties:
      fiscalNumber:
        type: "string"
        example: "RSSMRA80A01C351O"
      name:
        type: "string"
        example: "Mario"
      familyName:
        type: "string"
        example: "Rossi"
      identificationSerialCode:
        type: "string"
        example: "mariorossi@mail.com"
      identificationExpirationDate:
        type: "string"
        example: "mariorossi@mail.com"
      gender:
        type: "string"
        example: "M"
      dateOfBirth:
        type: "string"
        example: "mariorossi@mail.com"
      nationOfBirth:
        type: "string"
        example: "mariorossi@mail.com"
      email:
        type: "string"
        example: "mariorossi@mail.com"
      pec:
        type: "string"
        example: "mariorossi@mail.com"
      countryCallingCode:
        type: "string"
        example: "mariorossi@mail.com"
      phoneNumber:
        type: "string"
        example: "mariorossi@mail.com"
      
  ApiAuthResponse:
    type: "object"
    required:
    - "statusCode"
    - "authToken"
    properties:
      statusCode:
        type: "integer"
        example: "200"
      authToken:
        type: "string"
        example: "eyJ1c2VybmFtZSI6IkNpYW8ifQ:1lWcPE:a-vukHyF6j_sAxiHWSJ78wjeEqw"
